name: Publish
run-name: Publish ${{ github.ref_name }}

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    name: Publish Affise Libraries
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache Gradle and wrapper
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant Permission for Gradlew to Execute
        run: chmod +x gradlew

      # Publish
      - name: Nexus Publish
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SNAPSHOT: ${{ secrets.SNAPSHOT }}
        run: |
          ./gradlew :attribution:publishToSonatype closeAndReleaseSonatypeStagingRepository --no-daemon --no-parallel
          ./gradlew :module-advertising:publishToSonatype closeAndReleaseSonatypeStagingRepository --no-daemon --no-parallel
          ./gradlew :module-androidid:publishToSonatype closeAndReleaseSonatypeStagingRepository --no-daemon --no-parallel
          ./gradlew :module-link:publishToSonatype closeAndReleaseSonatypeStagingRepository --no-daemon --no-parallel
          ./gradlew :module-network:publishToSonatype closeAndReleaseSonatypeStagingRepository --no-daemon --no-parallel
          ./gradlew :module-phone:publishToSonatype closeAndReleaseSonatypeStagingRepository --no-daemon --no-parallel
          ./gradlew :module-status:publishToSonatype closeAndReleaseSonatypeStagingRepository --no-daemon --no-parallel
          ./gradlew :module-subscription:publishToSonatype closeAndReleaseSonatypeStagingRepository --no-daemon --no-parallel
          ./gradlew :module-rustore:publishToSonatype closeAndReleaseSonatypeStagingRepository --no-daemon --no-parallel
          ./gradlew :module-huawei:publishToSonatype closeAndReleaseSonatypeStagingRepository --no-daemon --no-parallel
          ./gradlew :internal:publishToSonatype closeAndReleaseSonatypeStagingRepository --no-daemon --no-parallel

      - name: Version Tag
        id: version_tag
        run: |
          echo Version: ${GITHUB_REF_NAME#v}
          echo "VERSION=${GITHUB_REF_NAME#v}" >> "$GITHUB_OUTPUT"

      # Release
      - name: Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Affise Attribution Android SDK ${{ github.ref }}
          draft: false
          prerelease: false

      # Release Upload Attribution library
      - name: Upload Release Attribution AAR 🗳
        id: upload-attribution-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: attribution/build/outputs/aar/attribution-release.aar
          asset_name: attribution-${{ steps.version_tag.outputs.VERSION }}.aar
          asset_content_type: application/aar

      # Release Upload Module Advertising
      - name: Upload Release Module Advertising AAR 🗳
        id: upload-module-advertising-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: module-advertising/build/outputs/aar/module-advertising-release.aar
          asset_name: module-advertising-${{ steps.version_tag.outputs.VERSION }}.aar
          asset_content_type: application/aar

      # Release Upload Module AndroidId
      - name: Upload Release Module AndroidId AAR 🗳
        id: upload-module-androidid-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: module-androidid/build/outputs/aar/module-androidid-release.aar
          asset_name: module-androidid-${{ steps.version_tag.outputs.VERSION }}.aar
          asset_content_type: application/aar

      # Release Upload Module Link
      - name: Upload Release Module Link AAR 🗳
        id: upload-module-link-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: module-link/build/outputs/aar/module-link-release.aar
          asset_name: module-link-${{ steps.version_tag.outputs.VERSION }}.aar
          asset_content_type: application/aar

      # Release Upload Module Network
      - name: Upload Release Module Network AAR 🗳
        id: upload-module-network-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: module-network/build/outputs/aar/module-network-release.aar
          asset_name: module-network-${{ steps.version_tag.outputs.VERSION }}.aar
          asset_content_type: application/aar

      # Release Upload Module Phone
      - name: Upload Release Module Phone AAR 🗳
        id: upload-module-phone-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: module-phone/build/outputs/aar/module-phone-release.aar
          asset_name: module-phone-${{ steps.version_tag.outputs.VERSION }}.aar
          asset_content_type: application/aar

      # Release Upload Module Status
      - name: Upload Release Module Status AAR 🗳
        id: upload-module-status-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: module-status/build/outputs/aar/module-status-release.aar
          asset_name: module-status-${{ steps.version_tag.outputs.VERSION }}.aar
          asset_content_type: application/aar

      # Release Upload Module Subscription
      - name: Upload Release Module Subscription AAR 🗳
        id: upload-module-subscription-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: module-subscription/build/outputs/aar/module-subscription-release.aar
          asset_name: module-subscription-${{ steps.version_tag.outputs.VERSION }}.aar
          asset_content_type: application/aar

      # Release Upload Module RuStore
      - name: Upload Release Module RuStore AAR 🗳
        id: upload-module-rustore-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: module-rustore/build/outputs/aar/module-rustore-release.aar
          asset_name: module-rustore-${{ steps.version_tag.outputs.VERSION }}.aar
          asset_content_type: application/aar

      # Release Upload Module Huawei
      - name: Upload Release Module Huawei AAR 🗳
        id: upload-module-huawei-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: module-huawei/build/outputs/aar/module-huawei-release.aar
          asset_name: module-huawei-${{ steps.version_tag.outputs.VERSION }}.aar
          asset_content_type: application/aar

#      # Release Upload Internal library
#      - name: Upload Release Internal AAR 🗳
#        id: upload-internal-asset
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ steps.create_release.outputs.upload_url }}
#          asset_path: internal/build/outputs/aar/internal-release.aar
#          asset_name: internal-${{ steps.version_tag.outputs.VERSION }}.aar
#          asset_content_type: application/aar

      # Demo App
      - name: Build Demo App
        if: ${{ !cancelled() }}
        run: |
          ./gradlew :app:assembleDebug --no-daemon --no-parallel

      # Release Upload Demo App
      - name: Upload Demo App 🗳
        if: ${{ !cancelled() }}
        id: upload-demo-app-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/debug/app-debug.apk
          asset_name: Affise-Demo-${{ steps.version_tag.outputs.VERSION }}.apk
          asset_content_type: application/vnd.android.package-archive
